/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITO = 1;
  /** RegularExpression Id. */
  int LETRA = 2;
  /** RegularExpression Id. */
  int SIMCORREO = 3;
  /** RegularExpression Id. */
  int GATU = 4;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int DECIMAL = 6;
  /** RegularExpression Id. */
  int EMAIL = 7;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 8;
  /** RegularExpression Id. */
  int URL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DIGITO>",
    "<LETRA>",
    "<SIMCORREO>",
    "<GATU>",
    "<NUMERO>",
    "<DECIMAL>",
    "<EMAIL>",
    "<IDENTIFICADOR>",
    "<URL>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
